/**
 * Demos de landings por rubro — rutas /demos/[slug].
 * Índice en /demos (sin enlace obligatorio desde la home).
 */

export type DemoMeta = {
  slug: string;
  title: string;
  industry: string;
  tagline: string;
  accent: string;
  previewClass: string;
};

export const DEMOS: DemoMeta[] = [
  {
    slug: "ferreteria",
    title: "Ferretería del Oeste",
    industry: "Ferretería & construcción",
    tagline: "Stock real, envíos y retiro en el día",
    accent: "#ea580c",
    previewClass: "from-zinc-900 to-orange-950",
  },
  {
    slug: "restaurante",
    title: "La Mesa Norteña",
    industry: "Restaurante & bar",
    tagline: "Reservas, carta y delivery en un click",
    accent: "#9f1239",
    previewClass: "from-rose-950 to-amber-950",
  },
  {
    slug: "estetica",
    title: "Aura Estética",
    industry: "Salón & spa",
    tagline: "Turnos online y promos por WhatsApp",
    accent: "#d4af37",
    previewClass: "from-stone-900 to-rose-900/40",
  },
  {
    slug: "gimnasio",
    title: "Pulse Cross",
    industry: "Gimnasio & box",
    tagline: "Planes, horarios y comunidad",
    accent: "#bef264",
    previewClass: "from-zinc-950 to-lime-950/50",
  },
  {
    slug: "veterinaria",
    title: "Patitas Sanas",
    industry: "Veterinaria & pet shop",
    tagline: "Guardia, vacunas y tienda de mascotas",
    accent: "#14b8a6",
    previewClass: "from-teal-950 to-cyan-900",
  },
  {
    slug: "inmobiliaria",
    title: "Horizonte Propiedades",
    industry: "Inmobiliaria",
    tagline: "Tasaciones y portfolio premium",
    accent: "#c5a572",
    previewClass: "from-slate-950 to-slate-800",
  },
  {
    slug: "tech",
    title: "Vanguardia Tech",
    industry: "SaaS & tecnología",
    tagline: "Infraestructura, IA soberana y sistemas distribuidos",
    accent: "#22d3ee",
    previewClass: "from-slate-950 via-cyan-950/25 to-slate-950",
  },
  {
    slug: "floreria",
    title: "Jardín Ensueño",
    industry: "Florería & vivero",
    tagline: "Plantas, ramos y talleres botánicos",
    accent: "#065f46",
    previewClass: "from-emerald-50 to-stone-100",
  },
  {
    slug: "taller",
    title: "Motor Dynamics",
    industry: "Taller mecánico & tuning",
    tagline: "Ingeniería de precisión y diagnóstico 4.0",
    accent: "#ea580c",
    previewClass: "from-zinc-950 to-orange-950/40",
  },
  {
    slug: "abogados",
    title: "Varela & Asociados",
    industry: "Estudio jurídico",
    tagline: "Defensa integral con prestigio y ética",
    accent: "#d97706",
    previewClass: "from-slate-950 to-amber-950/35",
  },
  {
    slug: "farmacia",
    title: "Farmacia Del Parque",
    industry: "Farmacia & salud",
    tagline: "Turno electrónico, obras sociales y delivery",
    accent: "#22c55e",
    previewClass: "from-emerald-950 to-green-900",
  },
  {
    slug: "odontologia",
    title: "Sonrisa Studio Dental",
    industry: "Odontología & implantes",
    tagline: "Diagnóstico digital, financiación y urgencias",
    accent: "#38bdf8",
    previewClass: "from-sky-950 to-cyan-950",
  },
  {
    slug: "contadores",
    title: "Número Exacto",
    industry: "Estudio contable & impuestos",
    tagline: "Monotributo, PyME y auditorías",
    accent: "#94a3b8",
    previewClass: "from-slate-900 to-slate-950",
  },
  {
    slug: "musica",
    title: "Pentagrama",
    industry: "Escuela de música",
    tagline: "Instrumentos, ensamble y examen Trinity demo",
    accent: "#c084fc",
    previewClass: "from-violet-950 to-fuchsia-950/50",
  },
  {
    slug: "detailing",
    title: "Shine Autodetail",
    industry: "Detailing & protección cerámica",
    tagline: "Pulido, PPF y tratamiento de interiores",
    accent: "#38bdf8",
    previewClass: "from-slate-950 to-blue-950/40",
  },
  {
    slug: "panaderia",
    title: "El Horno de Raíz",
    industry: "Panadería & café de especialidad",
    tagline: "Masa madre, pastelería y pedidos corporativos",
    accent: "#eab308",
    previewClass: "from-amber-950 to-orange-950/40",
  },
  {
    slug: "viajes",
    title: "Atlas Experiencias",
    industry: "Agencia de viajes & eventos",
    tagline: "Aéreos, cruceros y viajes a medida",
    accent: "#2dd4bf",
    previewClass: "from-teal-950 to-indigo-950/60",
  },
  {
    slug: "limpieza",
    title: "ProLimpio",
    industry: "Limpieza & facility",
    tagline: "Edificios, clínicas y plantas industriales demo",
    accent: "#818cf8",
    previewClass: "from-indigo-950 to-slate-900",
  },
  {
    slug: "foto",
    title: "Lúmenes Estudio",
    industry: "Fotografía & video comercial",
    tagline: "Producto, corporativo y cobertura de eventos",
    accent: "#f59e0b",
    previewClass: "from-zinc-900 to-amber-950/30",
  },
  {
    slug: "optica",
    title: "Visión Clara",
    industry: "Óptica & audiología",
    tagline: "Examen visual, lentes progresivos y audífonos",
    accent: "#60a5fa",
    previewClass: "from-blue-950 to-slate-950",
  },
  {
    slug: "heladeria",
    title: "Gelato Alborada",
    industry: "Heladería & cafetería",
    tagline: "Sabores de estación, delivery y eventos",
    accent: "#f472b6",
    previewClass: "from-fuchsia-900 to-cyan-950/60",
  },
  {
    slug: "lavadero",
    title: "Spin & Gloss Autolavado",
    industry: "Lavadero & detailing express",
    tagline: "Membership, filas inteligentes y app de turnos",
    accent: "#06b6d4",
    previewClass: "from-cyan-950 to-slate-950",
  },
  {
    slug: "seguridad",
    title: "Vigilum Alarmas",
    industry: "Seguridad electrónica & monitoreo",
    tagline: "Cámaras 4K, alarmas y central 24/7",
    accent: "#22c55e",
    previewClass: "from-emerald-950 to-zinc-950",
  },
  {
    slug: "yoga",
    title: "Mat Lumen",
    industry: "Yoga, pilates & breathwork",
    tagline: "Clases híbridas, retiros y corporativo",
    accent: "#a78bfa",
    previewClass: "from-violet-950 to-indigo-950",
  },
  {
    slug: "hotel",
    title: "Posada 9 Luces",
    industry: "Hotel boutique & rural premium",
    tagline: "Experiencias con spa, bodega y MICE chico",
    accent: "#d97706",
    previewClass: "from-amber-950 to-stone-900",
  },
  {
    slug: "catering",
    title: "Banquetes Origen",
    industry: "Catering & banquetes corporativos",
    tagline: "Degustaciones, cócteles y producción en sitio",
    accent: "#dc2626",
    previewClass: "from-red-950 to-neutral-950",
  },
  {
    slug: "paisajismo",
    title: "Verde Horizonte",
    industry: "Paisajismo & riego",
    tagline: "Diseño nativo, mantenimiento y smart irrigation",
    accent: "#16a34a",
    previewClass: "from-green-950 to-lime-950/40",
  },
  {
    slug: "tattoo",
    title: "Oráculo Ink Lab",
    industry: "Estudio de tatuaje & piercing",
    tagline: "Reservas, aftercare y merch de artista",
    accent: "#e11d48",
    previewClass: "from-rose-950 to-zinc-950",
  },
  {
    slug: "cerrajeria",
    title: "Llaves 24 Sur",
    industry: "Cerrajería & control de accesos",
    tagline: "Urgencias, vigilancia de cilindros y llaves maestras",
    accent: "#fcd34d",
    previewClass: "from-yellow-950 to-neutral-950",
  },
  {
    slug: "coworking",
    title: "Hub Muelle",
    industry: "Coworking & oficinas flex",
    tagline: "Day pass, cabinas fono y salas para equipos híbridos",
    accent: "#38bdf8",
    previewClass: "from-sky-900 to-slate-900",
  },
  {
    slug: "minecraft",
    title: "CubeNode",
    industry: "Hosting · Minecraft",
    tagline: "Java, Bedrock y modpacks en minutos",
    accent: "#22c55e",
    previewClass: "from-emerald-950 to-zinc-950",
  },
  {
    slug: "roblox",
    title: "BloxLayer",
    industry: "Hosting · Roblox",
    tagline: "Experiences privadas con escalado automático",
    accent: "#f43f5e",
    previewClass: "from-rose-950 to-zinc-950",
  },
  {
    slug: "cs2",
    title: "StrikeHost",
    industry: "Hosting · Counter-Strike 2",
    tagline: "128 tick, scrims y GOTV en la nube",
    accent: "#f59e0b",
    previewClass: "from-amber-950 to-neutral-950",
  },
  {
    slug: "fivem",
    title: "RoleNode",
    industry: "Hosting · GTA V FiveM",
    tagline: "RP serio con ESX, txAdmin y MariaDB",
    accent: "#a855f7",
    previewClass: "from-purple-950 to-zinc-950",
  },
  {
    slug: "muonline",
    title: "LegacyCore",
    industry: "Hosting · MU Online",
    tagline: "Season 6, anti-hack y launcher propio",
    accent: "#eab308",
    previewClass: "from-yellow-950 to-zinc-950",
  },
  {
    slug: "lineage2",
    title: "L2Forge",
    industry: "Hosting · Lineage II",
    tagline: "Chronicles, geodata y siege estable",
    accent: "#6366f1",
    previewClass: "from-indigo-950 to-slate-950",
  },
  {
    slug: "rust",
    title: "SurvivalGrid",
    industry: "Hosting · Rust",
    tagline: "Wipes programados y Oxide preinstalado",
    accent: "#cd412b",
    previewClass: "from-red-950 to-zinc-950",
  },
  {
    slug: "ark",
    title: "PrimalHost",
    industry: "Hosting · ARK",
    tagline: "Clusters, Workshop y backups de save",
    accent: "#14b8a6",
    previewClass: "from-teal-950 to-emerald-950/30",
  },
  {
    slug: "terraria",
    title: "TerraNode",
    industry: "Hosting · Terraria",
    tagline: "tModLoader, worlds en la nube y co-op",
    accent: "#a78bfa",
    previewClass: "from-violet-950 to-zinc-950",
  },
  {
    slug: "palworld",
    title: "PalCluster",
    industry: "Hosting · Palworld",
    tagline: "Dedicated co-op con saves protegidos",
    accent: "#06b6d4",
    previewClass: "from-cyan-950 to-slate-950",
  },
];

export const DEMO_SLUGS = DEMOS.map((d) => d.slug);

export function getDemoBySlug(slug: string): DemoMeta | undefined {
  return DEMOS.find((d) => d.slug === slug);
}
