/** Nueve capacidades por rubro para las cartillas del índice /demos. */
export type ShowcaseFeatures = readonly [
  string,
  string,
  string,
  string,
  string,
  string,
  string,
  string,
  string,
];

export const SHOWCASE_FEATURES: Record<string, ShowcaseFeatures> = {
  ferreteria: [
    "Control de stock",
    "Envíos y logística",
    "Panel / catálogo",
    "Cuenta corriente B2B",
    "Buscador por SKU",
    "Promos por zona",
    "Factura electrónica",
    "WhatsApp pedidos",
    "SEO local rubro",
  ],
  restaurante: [
    "Reservas online",
    "Carta y delivery",
    "Experiencia visual",
    "Menú estacional",
    "Maridajes y upsell",
    "Mapa de sucursales",
    "Reseñas integradas",
    "Gift cards",
    "Eventos privados",
  ],
  estetica: [
    "Agenda de turnos",
    "Catálogo de servicios",
    "WhatsApp CTA",
    "Protocolos premium",
    "Tienda home care",
    "Antes / después",
    "Membresía facial",
    "Blog bienestar",
    "Financiación visible",
  ],
  gimnasio: [
    "Planes y membresías",
    "Horarios en vivo",
    "Comunidad",
    "Shop nutrición",
    "Clases on-demand",
    "App check-in demo",
    "Entrenadores",
    "Prueba gratuita",
    "Eventos internos",
  ],
  veterinaria: [
    "Turnos y urgencias",
    "Pet shop",
    "Historias clínicas",
    "Recordatorio vacunas",
    "Planes antipulgas",
    "Guardia 24 h",
    "Delivery alimento",
    "Blog cuidados",
    "Seguros mascota",
  ],
  inmobiliaria: [
    "Portfolio filtrable",
    "Tours y fichas",
    "Leads calientes",
    "Tasaciones online",
    "Comparador barrios",
    "Calculadora hipoteca",
    "Alertas nuevas props",
    "Agentes destacados",
    "Mapa interactivo",
  ],
  tech: [
    "Trial y pricing",
    "Docs y API",
    "SLA y compliance",
    "Changelog público",
    "Integraciones",
    "Status page",
    "Casos enterprise",
    "Checkout add-ons",
    "Seguridad SOC2 demo",
  ],
  floreria: [
    "Catálogo y ramos",
    "Eventos",
    "Suscripciones",
    "Delivery mismo día",
    "Temporadas",
    "Dedicatorias",
    "Bodas y corporativo",
    "Fidelización",
    "Guía de cuidado",
  ],
  taller: [
    "Turnos mecánica",
    "Diagnóstico PDF",
    "Presupuesto online",
    "Repuestos originales",
    "Historial vehículo",
    "Garantía escrita",
    "Urgencias carretera",
    "Flota empresas",
    "Recordatorio service",
  ],
  abogados: [
    "Áreas de práctica",
    "Consulta inicial",
    "Confidencialidad",
    "Equipo y credenciales",
    "FAQ legal",
    "Blog jurisprudencia",
    "Formulario seguro",
    "Descarga guías",
    "Idiomas atención",
  ],
  farmacia: [
    "Turno y delivery",
    "Obras sociales",
    "OTC destacado",
    "Recetas digitales",
    "Cupones promo",
    "Dermocosmética",
    "Botiquín familiar",
    "Horario extendido",
    "Chat orientación",
  ],
  odontologia: [
    "Tratamientos",
    "Financiación",
    "Urgencias",
    "Primera visita",
    "Blanqueamiento",
    "Ortodoncia",
    "Implantes info",
    "Tienda cuidado",
    "Radiografía digital",
  ],
  contadores: [
    "Servicios impositivos",
    "PyME y monotributo",
    "Reporting",
    "Vencimientos AFIP",
    "Liquidación sueldos",
    "Auditorías",
    "Portal documentos",
    "Reuniones online",
    "Planes mensuales",
  ],
  musica: [
    "Cursos y niveles",
    "Exámenes",
    "Inscripción",
    "Alquiler instrumentos",
    "Ensamble estudiantil",
    "Calendario cuatrimestre",
    "Profes por instrumento",
    "Material digital",
    "Recitales y showcases",
  ],
  detailing: [
    "Paquetes detailing",
    "PPF y cerámico",
    "Turnos",
    "Antes / después",
    "Garantía coating",
    "Kit mantenimiento",
    "Flota premium",
    "Interior cuero",
    "Presupuesto express",
  ],
  panaderia: [
    "Catálogo fresco",
    "Encargues",
    "Café y lunch",
    "Masa madre",
    "Pedidos corporativos",
    "Horario horno",
    "Suscripción semanal",
    "Eventos catering",
    "Retiro programado",
  ],
  viajes: [
    "Cotizador paquetes",
    "Corporativo MICE",
    "Soporte 24/7",
    "Cruceros y aéreos",
    "Seguro viajero",
    "Itinerario PDF",
    "Seña online",
    "Experiencias locales",
    "Grupos escolares",
  ],
  limpieza: [
    "Facility",
    "Industrias y clínicas",
    "SLA KPI",
    "Reposición insumos",
    "Certificaciones",
    "Cotización edificio",
    "Turnos nocturnos",
    "Checklist digital",
    "Facturación central",
  ],
  foto: [
    "Packs foto y video",
    "E-commerce y hero",
    "Rush options",
    "Brief online",
    "Color grade",
    "Estudio producto",
    "Cobertura eventos",
    "Entrega nube",
    "Derechos de uso",
  ],
  optica: [
    "Examen y armazones",
    "Cristales progresivos",
    "Audiología",
    "Financiación cuotas",
    "Lentes contacto",
    "Ajuste express",
    "Garantía armazón",
    "Examen domicilio",
    "Guía salud visual",
  ],
  heladeria: [
    "Sabores rotativos",
    "Delivery y eventos",
    "Trazabilidad demo",
    "Tortas personalizadas",
    "Barra móvil",
    "Cadena de frío",
    "Menú estacional",
    "Pedidos anticipados",
    "Fidelización puntos",
  ],
  lavadero: [
    "Turno y membresía",
    "Túnel express",
    "Add-ons detailing",
    "QR sin fila",
    "Planes SUV",
    "App recordatorio",
    "Interior express",
    "Flota empresas",
    "Promo primer lavado",
  ],
  seguridad: [
    "CCTV y alarma",
    "Monitoreo 24/7",
    "Integraciones IoT",
    "Instalación 48 h",
    "App unificada",
    "Kits hogar y PyME",
    "Mantenimiento",
    "Auditoría sin cargo",
    "Garantía equipos",
  ],
  yoga: [
    "Studio híbrido",
    "Profes certificados",
    "B2B wellness",
    "Passes digitales",
    "Retiros finde",
    "Mat y merch",
    "Clases grabadas",
    "Descuento corporativo",
    "Calendario estilos",
  ],
  hotel: [
    "Booking engine",
    "Experiencias",
    "MICE boutique",
    "Late checkout",
    "Spa y gastronomía",
    "Tours locales",
    "Tarifas flexibles",
    "Reviews verificadas",
    "Check-in digital",
  ],
  catering: [
    "Briefing chef",
    "Logística en sitio",
    "Branding mesa",
    "Menú por persona",
    "Opciones dietéticas",
    "Coffee break",
    "Cóctel corporativo",
    "Seña online",
    "Staff en vivo",
  ],
  paisajismo: [
    "Diseño nativo",
    "Riego smart",
    "SLA mantenimiento",
    "Reporte fotográfico",
    "Contrato anual",
    "Poda programada",
    "Obra llave en mano",
    "Certificación riego",
    "Presupuesto jardín",
  ],
  tattoo: [
    "Reservas y seña",
    "Aftercare",
    "Merch artista",
    "Portfolio artistas",
    "Flash day",
    "Políticas claras",
    "Sesiones custom",
    "Cuidado piel",
    "Gift cards",
  ],
  cerrajeria: [
    "Urgencias 24 h",
    "Control de acceso",
    "Duplicados certificados",
    "Cilindros premium",
    "RFID consorcio",
    "Geolocalización móvil",
    "Garantía trabajo",
    "Tienda técnica",
    "Instalación certificada",
  ],
  coworking: [
    "Day pass",
    "Cabinas fono",
    "Salas híbridas",
    "Ocupación en vivo",
    "WiFi simétrico",
    "Café incluido",
    "Impresión y lockers",
    "Eventos networking",
    "Membresía equipo",
  ],
  minecraft: [
    "Panel Pterodactyl",
    "Modpacks 1-click",
    "Anti-DDoS L7",
    "Backups S3",
    "Subdominio gratis",
    "Java y Bedrock",
    "Soporte Discord",
    "Deploy < 90 s",
    "Migración mundos",
  ],
  roblox: [
    "API de despliegue",
    "Métricas en vivo",
    "Escalado horizontal",
    "CDN de assets",
    "Staging + prod",
    "Moderación roles",
    "Facturación pico",
    "Logs centralizados",
    "Whitelist export",
  ],
  cs2: [
    "128 tick fijo",
    "MetaMod + CSS",
    "GOTV en nube",
    "IP dedicada",
    "Rcon seguro",
    "Workshop rápido",
    "Retake / Surf",
    "Scrims PRO",
    "Anti-cheat demo",
  ],
  fivem: [
    "txAdmin incluido",
    "MariaDB local",
    "Artifacts al día",
    "Anti-DDoS UDP",
    "ESX / QBCore",
    "Voz optimizada",
    "Custom cars",
    "Onesync infinity",
    "Guía licencia GTA",
  ],
  muonline: [
    "Anti-hack classic",
    "Launcher branding",
    "SQL tuning",
    "Event scheduler",
    "Web registration",
    "Season 6 / Ex700",
    "Castle siege",
    "Migración SQL",
    "Cash shop panel",
  ],
  lineage2: [
    "Geodata incluida",
    "Login dedicado",
    "Panel de rates",
    "Backup SQL horario",
    "Website template",
    "Interlude · HF",
    "Olympiad fix",
    "Java y L2OFF",
    "Soporte castellano",
  ],
  rust: [
    "Oxide preinstalado",
    "RCON web",
    "Mapas custom",
    "Wipe scheduler",
    "Discord bot",
    "FPS boost flags",
    "2x / Kits",
    "Raid alerts",
    "Pop scaling",
  ],
  ark: [
    "Workshop auto",
    "Cluster transfer",
    "Savegame backup",
    "CPU turbo",
    "RCON avanzado",
    "ASA + Evolved",
    "Mods 50 GB",
    "Discord alerts",
    "PvE / PvP",
  ],
  terraria: [
    "tModLoader 1-click",
    "World vault",
    "Auto-save",
    "Panel móvil",
    "Calamity / Thorium",
    "Password server",
    "Vanilla + modded",
    "Snapshots",
    "Co-op estable",
  ],
  palworld: [
    "Save en NVMe",
    "Restart scheduler",
    "Whitelist",
    "Discord bot",
    "Low ping routing",
    "Updates guiados",
    "Co-op 8–32",
    "Backup patch",
    "Mods soportados",
  ],
  streamer: [
    "Overlays OBS",
    "Donaciones Ko-fi",
    "Media kit PDF",
    "Calendario streams",
    "Bot Discord",
    "Panel sponsors",
    "Alerts Streamlabs",
    "Shop merch",
    "VOD hub",
  ],
  youtuber: [
    "Grid de videos",
    "Media kit sponsors",
    "Lead magnet email",
    "Tarifas agents",
    "Blog comunidad",
    "Analytics demo",
    "Patreon link",
    "Shorts embed",
    "Course hub",
  ],
  tiktoker: [
    "Link in bio",
    "Stats en vivo",
    "Form UGC marcas",
    "Tienda digital",
    "Galería viral",
    "WhatsApp CTA",
    "Press kit",
    "Preset shop",
    "CRM collabs",
  ],
  comunicadores: [
    "Player episodios",
    "EPK prensa",
    "Booking charlas",
    "Sponsors",
    "Transcripciones SEO",
    "Newsletter",
    "RSS feed",
    "Multi-programa",
    "Portal partners",
  ],
  "taller-motos": [
    "Turnos online",
    "Catálogo repuestos",
    "Historial service",
    "Presupuesto WhatsApp",
    "Promos estacionales",
    "Mapa y horarios",
    "Mapa y horarios",
    "Mapa y horarios",
    "Mapa y horarios",
  ],
  celulares: [
    "Catálogo por marca",
    "Financiación visible",
    "Trade-in calculator",
    "Garantía oficial",
    "Accesorios bundle",
    "Pickup en local",
    "Pickup en local",
    "Pickup en local",
    "Pickup en local",
  ],
  almacen: [
    "Lista de precios",
    "Promos rotativas",
    "Pedido WhatsApp",
    "Zonas de envío",
    "Cupones barrio",
    "Horario extendido",
    "Horario extendido",
    "Horario extendido",
    "Horario extendido",
  ],
  kiosco: [
    "Combos destacados",
    "Menú por categoría",
    "Delivery express",
    "Horario nocturno",
    "Recargas demo",
    "Ubicación maps",
    "Ubicación maps",
    "Ubicación maps",
    "Ubicación maps",
  ],
  libreria: [
    "Listas escolares PDF",
    "Catálogo por nivel",
    "Reserva pick-up",
    "Ventas B2B",
    "Útiles destacados",
    "Blog tips estudio",
    "Blog tips estudio",
    "Blog tips estudio",
    "Blog tips estudio",
  ],
  bazar: [
    "Colecciones temporada",
    "Grid visual",
    "Ofertas destacadas",
    "Newsletter",
    "Mayorista demo",
    "Gift cards",
    "Gift cards",
    "Gift cards",
    "Gift cards",
  ],
  carniceria: [
    "Menú por corte",
    "Combos parrilla",
    "Delivery frío",
    "Recetas grill",
    "Pedido programado",
    "Mayorista",
    "Mayorista",
    "Mayorista",
    "Mayorista",
  ],
  granja: [
    "Caja semanal",
    "Suscripción mensual",
    "Tour campo",
    "Certificaciones",
    "Mayorista restaurantes",
    "Recetas",
    "Recetas",
    "Recetas",
    "Recetas",
  ],
  computacion: [
    "Armador de PC",
    "Catálogo componentes",
    "Tracking service",
    "Financiación",
    "Comparador specs",
    "Soporte remoto",
    "Soporte remoto",
    "Soporte remoto",
    "Soporte remoto",
  ],
  ropa: [
    "Lookbook editorial",
    "Filtro talles/color",
    "Outlet sección",
    "Guía de medidas",
    "Wishlist",
    "Envíos",
    "Envíos",
    "Envíos",
    "Envíos",
  ],
  supermercado: [
    "Folleto semanal",
    "Pasillos categoría",
    "Slots delivery",
    "Club puntos",
    "Ofertas 2x1",
    "Pick-up",
    "Pick-up",
    "Pick-up",
    "Pick-up",
  ],
  barberia: [
    "Reservas online",
    "Perfil barberos",
    "Membresía mensual",
    "Galería estilos",
    "Shop productos",
    "Recordatorios",
    "Recordatorios",
    "Recordatorios",
    "Recordatorios",
  ],
  marketing: [
    "Casos de éxito",
    "Paquetes servicios",
    "Blog SEO",
    "Form calificado",
    "Calculadora ROI",
    "Newsletter",
    "Newsletter",
    "Newsletter",
    "Newsletter",
  ],
  imprenta: [
    "Cotizador instantáneo",
    "Upload de archivos",
    "Tracking pedido",
    "Catálogo acabados",
    "Diseño gráfico",
    "Envío",
    "Envío",
    "Envío",
    "Envío",
  ],
  motores: [
    "Diagnóstico online",
    "Servicios por tipo motor",
    "Galería antes/después",
    "Presupuesto técnico",
    "Contratos flota",
    "Garantía",
    "Garantía",
    "Garantía",
    "Garantía",
  ],
  gasista: [
    "Matrícula visible",
    "Zonas de cobertura",
    "Botón urgencia",
    "Certificados gas",
    "Presupuesto visita",
    "Artefactos",
    "Artefactos",
    "Artefactos",
    "Artefactos",
  ],
  electricista: [
    "Galería de obras",
    "Presupuesto por foto",
    "Urgencias",
    "Instalaciones LED",
    "Tableros",
    "Mantenimiento",
    "Mantenimiento",
    "Mantenimiento",
    "Mantenimiento",
  ],
  albanil: [
    "Galería antes/después",
    "Presupuesto por m²",
    "Testimonios",
    "Cronograma obra",
    "Servicios lista",
    "Zonas",
    "Zonas",
    "Zonas",
    "Zonas",
  ],
  arquitectos: [
    "Portfolio editorial",
    "Renders destacados",
    "Proceso en etapas",
    "Form consulta",
    "Blog arquitectura",
    "Prensa",
    "Prensa",
    "Prensa",
    "Prensa",
  ],
};

export const FALLBACK_SHOWCASE_FEATURES: ShowcaseFeatures = [
  "Responsive mobile-first",
  "Performance optimizada",
  "Conversión y CTAs",
  "Galería demostrativa",
  "Video hero",
  "Testimonios",
  "E-commerce demo",
  "Formulario leads",
  "SEO estructurado",
];
