/**
 * Demos de landings por rubro — rutas /demos/[slug].
 * Índice en /demos (sin enlace obligatorio desde la home).
 */

import type { DemoSectorId } from "@/lib/demo-sectors";

export type DemoMeta = {
  slug: string;
  title: string;
  industry: string;
  tagline: string;
  accent: string;
  previewClass: string;
  /** Agrupa en el índice /demos por sector comercial. */
  sector?: DemoSectorId;
};

export const DEMOS: DemoMeta[] = [
  {
    slug: "ferreteria",
    title: "Ferretería del Oeste",
    industry: "Ferretería & construcción",
    tagline: "Stock real, envíos y retiro en el día",
    accent: "#ea580c",
    previewClass: "from-zinc-900 to-orange-950",
  },
  {
    slug: "herreria",
    title: "Forja Norte",
    industry: "Herrería & metalurgia",
    tagline: "Portones, estructuras y obra a medida",
    accent: "#f59e0b",
    previewClass: "from-stone-950 via-amber-950/40 to-stone-950",
  },
  {
    slug: "restaurante",
    title: "La Mesa Norteña",
    industry: "Restaurante & bar",
    tagline: "Reservas, carta y delivery en un click",
    accent: "#9f1239",
    previewClass: "from-rose-950 to-amber-950",
  },
  {
    slug: "estetica",
    title: "Aura Estética",
    industry: "Salón & spa",
    tagline: "Turnos online y promos por WhatsApp",
    accent: "#d4af37",
    previewClass: "from-stone-900 to-rose-900/40",
  },
  {
    slug: "gimnasio",
    title: "Pulse Cross",
    industry: "Gimnasio & box",
    tagline: "Planes, horarios y comunidad",
    accent: "#bef264",
    previewClass: "from-zinc-950 to-lime-950/50",
  },
  {
    slug: "veterinaria",
    title: "Patitas Sanas",
    industry: "Veterinaria & pet shop",
    tagline: "Guardia, vacunas y tienda de mascotas",
    accent: "#14b8a6",
    previewClass: "from-teal-950 to-cyan-900",
  },
  {
    slug: "inmobiliaria",
    title: "Horizonte Propiedades",
    industry: "Inmobiliaria",
    tagline: "Tasaciones y portfolio premium",
    accent: "#c5a572",
    previewClass: "from-slate-950 to-slate-800",
  },
  {
    slug: "tech",
    title: "Vanguardia Tech",
    industry: "SaaS & tecnología",
    tagline: "Infraestructura, IA soberana y sistemas distribuidos",
    accent: "#22d3ee",
    previewClass: "from-slate-950 via-cyan-950/25 to-slate-950",
  },
  {
    slug: "floreria",
    title: "Jardín Ensueño",
    industry: "Florería & vivero",
    tagline: "Plantas, ramos y talleres botánicos",
    accent: "#065f46",
    previewClass: "from-emerald-50 to-stone-100",
  },
  {
    slug: "taller",
    title: "Motor Dynamics",
    industry: "Taller mecánico & tuning",
    tagline: "Ingeniería de precisión y diagnóstico 4.0",
    accent: "#ea580c",
    previewClass: "from-zinc-950 to-orange-950/40",
  },
  {
    slug: "abogados",
    title: "Varela & Asociados",
    industry: "Estudio jurídico",
    tagline: "Defensa integral con prestigio y ética",
    accent: "#d97706",
    previewClass: "from-slate-950 to-amber-950/35",
  },
  {
    slug: "farmacia",
    title: "Galénica",
    industry: "Farmacia & salud · Medical Hub",
    tagline: "Tu salud, nuestra ciencia · 24/7",
    accent: "#0891b2",
    previewClass: "from-slate-50 to-cyan-100",
  },
  {
    slug: "odontologia",
    title: "Galénica Dental",
    industry: "Odontología · Dental Elite",
    tagline: "Odontología digital de precisión",
    accent: "#2563eb",
    previewClass: "from-slate-50 to-blue-100",
  },
  {
    slug: "contadores",
    title: "Número Exacto",
    industry: "Estudio contable & impuestos",
    tagline: "Monotributo, PyME y auditorías",
    accent: "#94a3b8",
    previewClass: "from-slate-900 to-slate-950",
  },
  {
    slug: "musica",
    title: "Pentagrama",
    industry: "Escuela de música",
    tagline: "Instrumentos, ensamble y examen Trinity demo",
    accent: "#c084fc",
    previewClass: "from-violet-950 to-fuchsia-950/50",
  },
  {
    slug: "detailing",
    title: "Shine Autodetail",
    industry: "Detailing & protección cerámica",
    tagline: "Pulido, PPF y tratamiento de interiores",
    accent: "#38bdf8",
    previewClass: "from-slate-950 to-blue-950/40",
  },
  {
    slug: "panaderia",
    title: "El Horno de Raíz",
    industry: "Panadería & café de especialidad",
    tagline: "Masa madre, pastelería y pedidos corporativos",
    accent: "#eab308",
    previewClass: "from-amber-950 to-orange-950/40",
  },
  {
    slug: "viajes",
    title: "Atlas Experiencias",
    industry: "Agencia de viajes & eventos",
    tagline: "Aéreos, cruceros y viajes a medida",
    accent: "#2dd4bf",
    previewClass: "from-teal-950 to-indigo-950/60",
  },
  {
    slug: "limpieza",
    title: "ProLimpio",
    industry: "Limpieza & facility",
    tagline: "Edificios, clínicas y plantas industriales demo",
    accent: "#818cf8",
    previewClass: "from-indigo-950 to-slate-900",
  },
  {
    slug: "foto",
    title: "Lúmenes Estudio",
    industry: "Fotografía & video comercial",
    tagline: "Producto, corporativo y cobertura de eventos",
    accent: "#f59e0b",
    previewClass: "from-zinc-900 to-amber-950/30",
  },
  {
    slug: "optica",
    title: "Visión Clara",
    industry: "Óptica & audiología",
    tagline: "Examen visual, lentes progresivos y audífonos",
    accent: "#60a5fa",
    previewClass: "from-blue-950 to-slate-950",
  },
  {
    slug: "heladeria",
    title: "Gelato Alborada",
    industry: "Heladería & cafetería",
    tagline: "Sabores de estación, delivery y eventos",
    accent: "#f472b6",
    previewClass: "from-fuchsia-900 to-cyan-950/60",
  },
  {
    slug: "lavadero",
    title: "Spin & Gloss Autolavado",
    industry: "Lavadero & detailing express",
    tagline: "Membership, filas inteligentes y app de turnos",
    accent: "#06b6d4",
    previewClass: "from-cyan-950 to-slate-950",
  },
  {
    slug: "seguridad",
    title: "Vigilum Alarmas",
    industry: "Seguridad electrónica & monitoreo",
    tagline: "Cámaras 4K, alarmas y central 24/7",
    accent: "#22c55e",
    previewClass: "from-emerald-950 to-zinc-950",
  },
  {
    slug: "yoga",
    title: "Mat Lumen",
    industry: "Yoga, pilates & breathwork",
    tagline: "Clases híbridas, retiros y corporativo",
    accent: "#a78bfa",
    previewClass: "from-violet-950 to-indigo-950",
  },
  {
    slug: "hotel",
    title: "Posada 9 Luces",
    industry: "Hotel boutique & rural premium",
    tagline: "Experiencias con spa, bodega y MICE chico",
    accent: "#d97706",
    previewClass: "from-amber-950 to-stone-900",
  },
  {
    slug: "catering",
    title: "Banquetes Origen",
    industry: "Catering & banquetes corporativos",
    tagline: "Degustaciones, cócteles y producción en sitio",
    accent: "#dc2626",
    previewClass: "from-red-950 to-neutral-950",
  },
  {
    slug: "paisajismo",
    title: "Verde Horizonte",
    industry: "Paisajismo & riego",
    tagline: "Diseño nativo, mantenimiento y smart irrigation",
    accent: "#16a34a",
    previewClass: "from-green-950 to-lime-950/40",
  },
  {
    slug: "tattoo",
    title: "Oráculo Ink Lab",
    industry: "Estudio de tatuaje & piercing",
    tagline: "Reservas, aftercare y merch de artista",
    accent: "#e11d48",
    previewClass: "from-rose-950 to-zinc-950",
  },
  {
    slug: "cerrajeria",
    title: "Llaves 24 Sur",
    industry: "Cerrajería & control de accesos",
    tagline: "Urgencias, vigilancia de cilindros y llaves maestras",
    accent: "#fcd34d",
    previewClass: "from-yellow-950 to-neutral-950",
  },
  {
    slug: "coworking",
    title: "Hub Muelle",
    industry: "Coworking & oficinas flex",
    tagline: "Day pass, cabinas fono y salas para equipos híbridos",
    accent: "#38bdf8",
    previewClass: "from-sky-900 to-slate-900",
  },
  {
    slug: "minecraft",
    title: "CubeNode",
    industry: "Hosting · Minecraft",
    tagline: "Java, Bedrock y modpacks en minutos",
    accent: "#22c55e",
    previewClass: "from-emerald-950 to-zinc-950",
  },
  {
    slug: "roblox",
    title: "BloxLayer",
    industry: "Hosting · Roblox",
    tagline: "Experiences privadas con escalado automático",
    accent: "#f43f5e",
    previewClass: "from-rose-950 to-zinc-950",
  },
  {
    slug: "cs2",
    title: "StrikeHost",
    industry: "Hosting · Counter-Strike 2",
    tagline: "128 tick, scrims y GOTV en la nube",
    accent: "#f59e0b",
    previewClass: "from-amber-950 to-neutral-950",
  },
  {
    slug: "fivem",
    title: "RoleNode",
    industry: "Hosting · GTA V FiveM",
    tagline: "RP serio con ESX, txAdmin y MariaDB",
    accent: "#a855f7",
    previewClass: "from-purple-950 to-zinc-950",
  },
  {
    slug: "muonline",
    title: "LegacyCore",
    industry: "Hosting · MU Online",
    tagline: "Season 6, anti-hack y launcher propio",
    accent: "#eab308",
    previewClass: "from-yellow-950 to-zinc-950",
  },
  {
    slug: "lineage2",
    title: "L2Forge",
    industry: "Hosting · Lineage II",
    tagline: "Chronicles, geodata y siege estable",
    accent: "#6366f1",
    previewClass: "from-indigo-950 to-slate-950",
  },
  {
    slug: "rust",
    title: "SurvivalGrid",
    industry: "Hosting · Rust",
    tagline: "Wipes programados y Oxide preinstalado",
    accent: "#cd412b",
    previewClass: "from-red-950 to-zinc-950",
  },
  {
    slug: "ark",
    title: "PrimalHost",
    industry: "Hosting · ARK",
    tagline: "Clusters, Workshop y backups de save",
    accent: "#14b8a6",
    previewClass: "from-teal-950 to-emerald-950/30",
  },
  {
    slug: "terraria",
    title: "TerraNode",
    industry: "Hosting · Terraria",
    tagline: "tModLoader, worlds en la nube y co-op",
    accent: "#a78bfa",
    previewClass: "from-violet-950 to-zinc-950",
  },
  {
    slug: "palworld",
    title: "PalCluster",
    industry: "Hosting · Palworld",
    tagline: "Dedicated co-op con saves protegidos",
    accent: "#06b6d4",
    previewClass: "from-cyan-950 to-slate-950",
  },
  {
    slug: "streamer",
    title: "NeoStream",
    industry: "Streamer · Twitch & Kick",
    tagline: "Overlays, donaciones y media kit en un hub",
    accent: "#9146ff",
    previewClass: "from-violet-950 to-slate-950",
  },
  {
    slug: "youtuber",
    title: "FrameLab",
    industry: "YouTuber · long-form",
    tagline: "Funnels de sponsors y biblioteca de videos",
    accent: "#ff0000",
    previewClass: "from-red-950 to-slate-950",
  },
  {
    slug: "tiktoker",
    title: "ViralPulse",
    industry: "TikToker · short-form",
    tagline: "Link in bio, UGC y formulario de marcas",
    accent: "#25f4ee",
    previewClass: "from-cyan-950 via-fuchsia-950 to-slate-950",
  },
  {
    slug: "comunicadores",
    title: "OnAir Media",
    industry: "Podcast & comunicación",
    tagline: "Episodios, prensa y booking de charlas",
    accent: "#f59e0b",
    previewClass: "from-amber-950 to-slate-950",
  },
  {
    slug: "taller-motos",
    title: "MotoForge",
    industry: "Taller de motos",
    tagline: "Service · repuestos · turnos",
    accent: "#f97316",
    previewClass: "from-orange-950 to-zinc-950",
  },
  {
    slug: "celulares",
    title: "CellPoint",
    industry: "Casa de celulares",
    tagline: "Equipos · accesorios · garantía",
    accent: "#3b82f6",
    previewClass: "from-blue-950 to-slate-950",
  },
  {
    slug: "almacen",
    title: "Depósito Norte",
    industry: "Almacén & autoservicio",
    tagline: "Ofertas · delivery · fidelidad",
    accent: "#d97706",
    previewClass: "from-amber-950 to-stone-950",
  },
  {
    slug: "kiosco",
    title: "Kiosko 24",
    industry: "Kiosco & maxikiosco",
    tagline: "Snacks · bebidas · recargas",
    accent: "#eab308",
    previewClass: "from-yellow-950 to-zinc-950",
  },
  {
    slug: "libreria",
    title: "Página & Tinta",
    industry: "Librería & papelería",
    tagline: "Útiles · libros · universidad",
    accent: "#92400e",
    previewClass: "from-amber-950/80 to-stone-900",
  },
  {
    slug: "bazar",
    title: "Bazar Central",
    industry: "Bazar & variedades",
    tagline: "Hogar · regalos · temporada",
    accent: "#ec4899",
    previewClass: "from-pink-950 to-rose-950",
  },
  {
    slug: "carniceria",
    title: "Cortes Don Juan",
    industry: "Carnicería premium",
    tagline: "Cortes · parrilla · delivery",
    accent: "#dc2626",
    previewClass: "from-red-950 to-zinc-950",
  },
  {
    slug: "granja",
    title: "Campo Vivo",
    industry: "Granja & agro",
    tagline: "Huevos · verduras · suscripción",
    accent: "#16a34a",
    previewClass: "from-green-950 to-emerald-950",
  },
  {
    slug: "computacion",
    title: "ChipHouse",
    industry: "Casa de computación",
    tagline: "PCs · notebooks · service",
    accent: "#06b6d4",
    previewClass: "from-cyan-950 to-slate-950",
  },
  {
    slug: "ropa",
    title: "Urbana Moda",
    industry: "Tienda de ropa",
    tagline: "Colecciones · talles · lookbook",
    accent: "#db2777",
    previewClass: "from-fuchsia-950 to-zinc-950",
  },
  {
    slug: "supermercado",
    title: "Mercado Familiar",
    industry: "Supermercado",
    tagline: "Góndola · ofertas · delivery",
    accent: "#059669",
    previewClass: "from-emerald-950 to-green-950",
  },
  {
    slug: "barberia",
    title: "The Fade Club",
    industry: "Barbería & grooming",
    tagline: "Turnos · barbas · membresía",
    accent: "#64748b",
    previewClass: "from-slate-800 to-zinc-950",
  },
  {
    slug: "marketing",
    title: "Pulse Agency",
    industry: "Agencia de marketing",
    tagline: "Ads · branding · funnels",
    accent: "#8b5cf6",
    previewClass: "from-violet-950 to-indigo-950",
  },
  {
    slug: "imprenta",
    title: "PrintLab",
    industry: "Imprenta & gráfica",
    tagline: "Tarjetas · gigantografía · packs",
    accent: "#4f46e5",
    previewClass: "from-indigo-950 to-slate-950",
  },
  {
    slug: "motores",
    title: "MotorTech",
    industry: "Service técnico de motores",
    tagline: "Rectificación · diagnóstico",
    accent: "#c2410c",
    previewClass: "from-orange-950 to-red-950",
  },
  {
    slug: "gasista",
    title: "GasSeguro",
    industry: "Gasista matriculado",
    tagline: "Matrícula · artefactos · urgencias",
    accent: "#0284c7",
    previewClass: "from-sky-950 to-blue-950",
  },
  {
    slug: "electricista",
    title: "VoltPro",
    industry: "Electricista",
    tagline: "Instalaciones · tableros · LED",
    accent: "#ca8a04",
    previewClass: "from-yellow-950 to-amber-950",
  },
  {
    slug: "albanil",
    title: "AlbaPro",
    industry: "Albañilería & reformas",
    tagline: "Reformas · revoques · ampliaciones",
    accent: "#78716c",
    previewClass: "from-stone-800 to-zinc-950",
  },
  {
    slug: "arquitectos",
    title: "Línea Estudio",
    industry: "Estudio de arquitectura",
    tagline: "Proyectos · renders · dirección",
    accent: "#a8a29e",
    previewClass: "from-stone-700 to-neutral-950",
  },
  {
    slug: "moda-infinita",
    title: "INFINITA",
    industry: "Tienda de ropa · boutique",
    tagline: "L'Élégance Absolue · Ezeiza",
    accent: "#fafafa",
    previewClass: "from-zinc-950 via-black to-zinc-900",
    sector: "moda-retail",
  },
  {
    slug: "moda-maison-elle",
    title: "Maison Elle",
    industry: "Tienda de ropa · boutique",
    tagline: "Silhouettes atemporales · Palermo",
    accent: "#d6d3d1",
    previewClass: "from-stone-200 to-stone-900",
    sector: "moda-retail",
  },
  {
    slug: "moda-atelier-noir",
    title: "Atelier Noir",
    industry: "Tienda de ropa · boutique",
    tagline: "Dark luxury · Recoleta",
    accent: "#525252",
    previewClass: "from-black to-zinc-800",
    sector: "moda-retail",
  },
  {
    slug: "moda-luna-boutique",
    title: "Luna Boutique",
    industry: "Tienda de ropa · boutique",
    tagline: "Noche de gala · San Telmo",
    accent: "#c4b5fd",
    previewClass: "from-indigo-950 to-black",
    sector: "moda-retail",
  },
  {
    slug: "moda-silk-atelier",
    title: "Silk Atelier",
    industry: "Tienda de ropa · boutique",
    tagline: "Alta costura en seda · Belgrano",
    accent: "#fde68a",
    previewClass: "from-amber-100 to-stone-900",
    sector: "moda-retail",
  },
  {
    slug: "moda-casa-nova",
    title: "Casa Nova",
    industry: "Tienda de ropa · boutique",
    tagline: "Moda de autor · Villa Crespo",
    accent: "#f97316",
    previewClass: "from-orange-950 to-zinc-950",
    sector: "moda-retail",
  },
  {
    slug: "moda-linnea",
    title: "Linnea",
    industry: "Tienda de ropa · boutique",
    tagline: "Minimal nordic · Nordelta",
    accent: "#e7e5e4",
    previewClass: "from-stone-100 to-stone-800",
    sector: "moda-retail",
  },
  {
    slug: "moda-maison-rose",
    title: "Maison Rosé",
    industry: "Tienda de ropa · boutique",
    tagline: "Femme délicate · Olivos",
    accent: "#fda4af",
    previewClass: "from-rose-100 to-rose-950",
    sector: "moda-retail",
  },
  {
    slug: "moda-urbano-chic",
    title: "Urbano Chic",
    industry: "Tienda de ropa · boutique",
    tagline: "Street luxury · Caballito",
    accent: "#a3e635",
    previewClass: "from-lime-400 to-zinc-950",
    sector: "moda-retail",
  },
  {
    slug: "moda-vogue-estudio",
    title: "Vogue Estudio",
    industry: "Tienda de ropa · boutique",
    tagline: "Imagen editorial · Microcentro",
    accent: "#94a3b8",
    previewClass: "from-slate-400 to-black",
    sector: "moda-retail",
  },
  {
    slug: "moda-andrea-mari",
    title: "Showroom Andrea Mari",
    industry: "Tienda de ropa · talles reales",
    tagline: "Moda vibrante · curva completa · Ezeiza",
    accent: "#D81159",
    previewClass: "from-fuchsia-600 via-amber-400 to-sky-950",
    sector: "moda-retail",
  },
  {
    slug: "moda-showroom-weekend",
    title: "Showroom Weekend",
    industry: "Tienda de ropa · talles reales",
    tagline: "Moda tech · probador virtual · Ezeiza",
    accent: "#f43f5e",
    previewClass: "from-rose-600 via-pink-500 to-slate-950",
    sector: "moda-retail",
  },
  {
    slug: "moda-arana-283",
    title: "ARANA 283",
    industry: "Moda circular · compra-venta",
    tagline: "Streetwear premium · Ezeiza",
    accent: "#a855f7",
    previewClass: "from-purple-600 via-pink-500 to-zinc-950",
    sector: "moda-retail",
  },
  {
    slug: "the-barber-club",
    title: "The Barber Club",
    industry: "Barbería premium & grooming",
    tagline: "Turnos · shop · membresías VIP",
    accent: "#f59e0b",
    previewClass: "from-amber-600 via-zinc-900 to-black",
  },
  {
    slug: "masa-madre-co",
    title: "Masa Madre & Co.",
    industry: "Panadería & pastelería artesanal",
    tagline: "Pedidos online · horno en vivo · Ezeiza",
    accent: "#c2410c",
    previewClass: "from-orange-100 via-amber-50 to-stone-200",
  },
  {
    slug: "nido-linaje",
    title: "Nido & Linaje",
    industry: "Blanquería premium · home textiles",
    tagline: "Couture · variantes · checkout de lujo",
    accent: "#78716c",
    previewClass: "from-stone-50 via-white to-slate-50",
  },
  {
    slug: "central-bebidas",
    title: "Central de Bebidas",
    industry: "Distribuidora mayorista y minorista",
    tagline: "B2B/B2C · combos · WhatsApp depósito",
    accent: "#a3e635",
    previewClass: "from-zinc-950 via-zinc-900 to-lime-950",
  },
];

export const DEMO_SLUGS = DEMOS.map((d) => d.slug);

export function getDemoBySlug(slug: string): DemoMeta | undefined {
  return DEMOS.find((d) => d.slug === slug);
}
